#pragma once

#include <cstdint>
#include <deque>
#include <functional>
#include <map>

#include "../trading/order.h"

namespace matching {

class LimitOrderBook {
 public:
  // Adds an order and returns the ID assigned to it.
  std::uint64_t add_order(trading::Order order);

  void print() const;

 private:
  using Price = std::int64_t;

  using OrderQueue = std::deque<trading::Order>;

  // IDs are generated by the order book.
  // Start at 1 so that 0 can remain an "invalid/unassigned" ID.
  std::uint64_t next_order_id_ = 1;

  // Bids:
  // Highest price has priority, so prices are sorted descending.
  std::map<Price, OrderQueue, std::greater<Price>> bids_;

  // Asks:
  // Lowest price has priority, so prices are sorted ascending.
  std::map<Price, OrderQueue> asks_;
};

}  // namespace matching
