#pragma once

#include <cstdint>
#include <deque>
#include <functional>
#include <map>

#include "../trading/order.h"

namespace matching {

class LimitOrderBook {
 public:
  // Adds an order and returns the ID assigned to it.
  std::uint64_t add_order(trading::Order order);

  // Removes an existing order.
  // Returns false if order ID does not exist.
  bool cancel_order(std::uint64_t order_id);

  void print() const;

 private:
  using Price = std::int64_t;
  using OrderQueue = std::deque<trading::Order>;

  struct OrderLocation {
    trading::Side side;
    Price price;
  };

  // IDs are generated by the order book.
  // Start at 1 so that 0 can remain an "invalid/unassigned" ID.
  std::uint64_t next_order_id_ = 1;

  // Bids:
  // Highest price has priority, so prices are sorted descending.
  std::map<Price, OrderQueue, std::greater<Price>> bids_;

  // Asks:
  // Lowest price has priority, so prices are sorted ascending.
  std::map<Price, OrderQueue> asks_;

  // Secondary index used to find the order's price level quickly.
  //
  // The order book needs both:
  //
  //  price -> orders
  //
  // for matching, and:
  //
  //  order ID -> location
  //
  // for cancellation.
  std::unordered_map<std::uint64_t, OrderLocation> order_index_;
};

}  // namespace matching
