#pragma once

#include <deque>
#include <functional>
#include <map>

#include "../trading/order.h"
#include "../trading/trade.h"
#include "../types.h"

namespace matching {

class LimitOrderBook {
 public:
  // |expected_order_count| is used to reserve space for |order_index_|.
  // A value of 0 keeps the default behavior.
  explicit LimitOrderBook(usize expected_order_count = 0);

  // Adds an order, performs any possible matches, and returns the trades
  // generated by the matching process.
  std::vector<trading::Trade> AddOrder(trading::Order order);

  // Removes an existing order.
  // Returns false if order ID does not exist.
  bool32 CancelOrder(uint64 order_id);

  void Print() const;

 private:
  using Price = int64;
  using OrderQueue = std::deque<trading::Order>;

  struct OrderLocation {
    trading::Side side;
    Price price;
  };

  // IDs are generated by the order book.
  // Start at 1 so that 0 can remain an "invalid/unassigned" ID.
  uint64 next_order_id_ = 1;

  // Bids:
  // Highest price has priority, so prices are sorted descending.
  std::map<Price, OrderQueue, std::greater<Price>> bids_;

  // Asks:
  // Lowest price has priority, so prices are sorted ascending.
  std::map<Price, OrderQueue> asks_;

  // Secondary index used to find the order's price level quickly.
  //
  // The order book needs both:
  //
  //  price -> orders
  //
  // for matching, and:
  //
  //  order ID -> location
  //
  // for cancellation.
  std::unordered_map<uint64, OrderLocation> order_index_;
};

}  // namespace matching
